# Generated by Django 2.1.2 on 2018-10-28 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminssh',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.Area'),
        ),
    ]
