# Generated by Django 2.1.2 on 2018-10-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_auto_20181028_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
