# Generated by Django 2.1.2 on 2018-10-29 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0007_auto_20181029_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminssh',
            name='id',
        ),
        migrations.AlterField(
            model_name='adminssh',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Location.Area'),
        ),
        migrations.AlterField(
            model_name='area',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
