# Generated by Django 2.1.2 on 2018-11-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssh', '0003_auto_20181108_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessssh',
            name='permission',
        ),
    ]
