# Generated by Django 2.1.2 on 2018-11-11 13:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ssh', '0004_remove_accessssh_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('list', models.ManyToManyField(to='ssh.BlackList')),
                ('ssh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssh.SSH')),
            ],
        ),
    ]
