# Generated by Django 2.1.2 on 2018-11-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssh', '0006_auto_20181111_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeblacklist',
            name='list',
        ),
        migrations.AddField(
            model_name='timeblacklist',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ssh.BlackList'),
        ),
    ]
