# Generated by Django 2.1.2 on 2018-11-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssh', '0007_auto_20181116_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeblacklist',
            old_name='list',
            new_name='cmd',
        ),
    ]
