# Generated by Django 2.1.2 on 2018-11-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssh', '0009_accessssh_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logcommand',
            name='connection',
        ),
        migrations.AddField(
            model_name='logcommand',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ssh.SSH'),
        ),
    ]
