# Generated by Django 2.1.2 on 2018-12-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssh', '0013_granthistory_ssh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='granthistory',
            name='ssh',
        ),
        migrations.AddField(
            model_name='granthistory',
            name='ssh',
            field=models.ManyToManyField(to='ssh.SSH'),
        ),
    ]
