# Generated by Django 2.1.2 on 2018-12-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssh', '0016_auto_20181223_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='granthistory',
            name='ssh',
        ),
    ]
