# Generated by Django 2.1.2 on 2018-12-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssh', '0017_remove_granthistory_ssh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granthistory',
            name='log',
            field=models.TextField(default='', max_length=100),
        ),
    ]
